### ISSUE TITLE
New process started before current process has finished its bootstrapping

### ISSUE THREAD

**Issue by iandanforth** [araffin/rl-baselines-zoo#8]
**Describe the bug**

There is a race condition in the multi-processing lib if you don't use 

```
if __name__ == "__main__":
    main()
```

**System Info**

OS: Windows 10
Installed: via pip
GPU: 970
Python: 3.6.5

**Additional context**

C:\Users\Ian\clones\rl-baselines-zoo>python enjoy.py --algo ppo2 --env Walker2DBulletEnv-v0
pybullet build time: Jan 11 2019 15:30:44
c:\users\ian\clones\gym\gym\logger.py:30: UserWarning: [33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
pybullet build time: Jan 11 2019 15:30:44
c:\users\ian\clones\gym\gym\logger.py:30: UserWarning: [33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ian\clones\rl-baselines-zoo\enjoy.py", line 59, in <module>
    seed=args.seed, log_dir=log_dir, should_render=not args.no_render)
  File "C:\Users\Ian\clones\rl-baselines-zoo\utils\utils.py", line 115, in create_test_env
    env = SubprocVecEnv([make_env(env_id, 0, seed, log_dir)])
  File "c:\users\ian\clones\stable-baselines\stable_baselines\common\vec_env\subproc_vec_env.py", line 59, in __init__
    process.start()
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Ian\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by araffin** [comment]
Hello,
Thanks for reporting this issue.
related to https://github.com/hill-a/stable-baselines/issues/155
I think some documentation is missing in stable-baselines
